version: '3.8'

services:
  nginx-brute:
    build: ./nginx
    networks:
      - mger
    volumes:
      - type: bind
        source: ./site
        target: /var/www/html/
        read_only: true
    ports:
      - 8080:80

  php-brute:
    build: ./php
    volumes:
      - type: bind
        source: ./site
        target: /var/www/html/
        read_only: true
    networks:
      - mger

  mysql-brute:
    image: mysql
    env_file:
      - .env

networks:
  mger:
    driver: bridge